In [98]:
import pandas as pd
import numpy as np

c1=pd.read_csv('C:/Users/saket/Downloads/Population-by-state.csv', header =1)
pd.DataFrame(c1)
c1

,Id,Id2,Geography,"April 1, 2010 - Census","April 1, 2010 - Estimates Base",Population Estimate (as of July 1) - 2010,Population Estimate (as of July 1) - 2011,Population Estimate (as of July 1) - 2012,Population Estimate (as of July 1) - 2013,Population Estimate (as of July 1) - 2014,Population Estimate (as of July 1) - 2015,Population Estimate (as of July 1) - 2016
0,0400000US01,1,Alabama,4779736,4780131,4785492,4799918,4815960,4829479,4843214,4853875,4863300
1,0400000US02,2,Alaska,710231,710249,714031,722713,731089,736879,736705,737709,741894
2,0400000US04,4,Arizona,6392017,6392301,6408312,6467163,6549634,6624617,6719993,6817565,6931071
3,0400000US05,5,Arkansas,2915918,2916025,2921995,2939493,2950685,2958663,2966912,2977853,2988248
4,0400000US06,6,California,37253956,37254522,37332685,37676861,38011074,38335203,38680810,38993940,39250017
5,0400000US08,8,Colorado,5029196,5029324,5048644,5118360,5189867,5267603,5349648,5448819,5540545
6,0400000US09,9,Connecticut,3574097,3574114,3579899,3589893,3593795,3596003,3591873,3584730,3576452
7,0400000US10,10,Delaware,897934,897936,899816,907924,916993,925395,934948,944076,952065
8,0400000US11,11,District of Columbia,601723,601766,605183,620477,635327,649165,659005,670377,681170
9,0400000US12,12,Florida,18801310,18804592,18849098,19096952,19344156,19582022,19888741,20244914,20612439
10,0400000US13,13,Georgia,9687653,9688680,9713521,9811610,9914668,9984938,10087231,10199398,10310371
11,0400000US15,15,Hawaii,1360301,1360301,1363945,1377864,1391820,1406481,1416349,1425157,1428557
12,0400000US16,16,Idaho,1567582,1567650,1571010,1584143,1595911,1612011,1633532,1652828,1683140
13,0400000US17,17,Illinois,12830632,12831574,12841578,12860012,12870798,12879505,12867544,12839047,12801539
14,0400000US18,18,Indiana,6483802,6484136,6490528,6516480,6537743,6569102,6595233,6612768,6633053
15,0400000US19,19,Iowa,3046355,3046869,3050738,3065223,3076310,3091930,3108030,3121997,3134693
16,0400000US20,20,Kansas,2853118,2853129,2858850,2869503,2885262,2892821,2899360,2906721,2907289
17,0400000US21,21,Kentucky,4339367,4339344,4348662,4369354,4384799,4400477,4413057,4424611,4436974
18,0400000US22,22,Louisiana,4533372,4533479,4544996,4575404,4603429,4626402,4647880,4668960,4681666
19,0400000US23,23,Maine,1328361,1328364,1327730,1328231,1328895,1329076,1330719,1329453,1331479
20,0400000US24,24,Maryland,5773552,5773786,5788584,5843603,5889651,5931129,5967295,5994983,6016447
21,0400000US25,25,Massachusetts,6547629,6547813,6565524,6611923,6658008,6706786,6749911,6784240,6811779
22,0400000US26,26,Michigan,9883640,9884129,9877495,9876213,9887238,9898982,9915767,9917715,9928300
23,0400000US27,27,Minnesota,5303925,5303924,5311147,5348562,5380285,5418521,5453109,5482435,5519952
24,0400000US28,28,Mississippi,2967297,2968103,2970322,2978162,2984945,2990482,2992400,2989390,2988726
25,0400000US29,29,Missouri,5988927,5988928,5996118,6010717,6025415,6042711,6060930,6076204,6093000
26,0400000US30,30,Montana,989415,989414,990641,997821,1005196,1014314,1022867,1032073,1042520
27,0400000US31,31,Nebraska,1826341,1826334,1830051,1842283,1855725,1868559,1881145,1893765,1907116
28,0400000US32,32,Nevada,2700551,2700691,2703284,2718379,2752565,2786464,2833013,2883758,2940058
29,0400000US33,33,New Hampshire,1316470,1316461,1316872,1318473,1321182,1322687,1328743,1330111,1334795
30,0400000US34,34,New Jersey,8791894,8791953,8803729,8841243,8873211,8899162,8925001,8935421,8944469
31,0400000US35,35,New Mexico,2059179,2059198,2064756,2077756,2083784,2085193,2083024,2080328,2081015
32,0400000US36,36,New York,19378102,19378110,19402640,19519529,19602769,19673546,19718515,19747183,19745289
33,0400000US37,37,North Carolina,9535483,9535688,9558915,9650963,9746175,9841590,9934399,10035186,10146788
34,0400000US38,38,North Dakota,672591,672591,674526,685476,702087,724019,739904,756835,757952
35,0400000US39,39,Ohio,11536504,11536727,11540983,11544824,11550839,11570022,11594408,11605090,11614373
36,0400000US40,40,Oklahoma,3751351,3751615,3759603,3786274,3817054,3852415,3877499,3907414,3923561
37,0400000US41,41,Oregon,3831074,3831072,3838048,3868031,3899116,3925751,3968371,4024634,4093465
38,0400000US42,42,Pennsylvania,12702379,12702857,12712343,12744293,12771854,12781338,12790565,12791904,12784227
39,0400000US44,44,Rhode Island,1052567,1052940,1053337,1052451,1052901,1053033,1054480,1055607,1056426
40,0400000US45,45,South Carolina,4625364,4625410,4635943,4672637,4720760,4767894,4828430,4894834,4961119
41,0400000US46,46,South Dakota,814180,814195,816325,824398,834441,844922,852561,857919,865454
42,0400000US47,47,Tennessee,6346105,6346298,6356671,6397634,6454306,6494821,6544663,6595056,6651194
43,0400000US48,48,Texas,25145561,25146100,25244310,25646389,26071655,26473525,26944751,27429639,27862596
44,0400000US49,49,Utah,2763885,2763888,2775326,2816124,2855782,2902663,2941836,2990632,3051217
45,0400000US50,50,Vermont,625741,625741,625982,626730,626444,627140,626984,626088,624594
46,0400000US51,51,Virginia,8001024,8001041,8025773,8110035,8192048,8262692,8317372,8367587,8411808
47,0400000US53,53,Washington,6724540,6724545,6743226,6822520,6895226,6968006,7054196,7160290,7288000
48,0400000US54,54,West Virginia,1852994,1853011,1854230,1854972,1856560,1853231,1848514,1841053,1831102
49,0400000US55,55,Wisconsin,5686986,5687289,5690263,5709640,5726177,5742854,5758377,5767891,5778708
50,0400000US56,56,Wyoming,563626,563767,564513,567725,576765,582684,583642,586555,585501
51,0400000US72,72,Puerto Rico,3725789,3726157,3721525,3678732,3634488,3593077,3534874,3473181,3411307

In [99]:
estimate_columns =[' Population Estimate (as of July 1) - 2010',
    'Population Estimate (as of July 1) - 2011',
    'Population Estimate (as of July 1) - 2012',
    'Population Estimate (as of July 1) - 2013',
    'Population Estimate (as of July 1) - 2014',
    'Population Estimate (as of July 1) - 2015',
    'Population Estimate (as of July 1) - 2016'
                  ]

In [100]:
c1['Population Estimate (as of July 1) - 2010'].sum(axis=0)

313069718

#Challenge 1

In [101]:
import pandas as pd


estimate_columns = [
    'Population Estimate (as of July 1) - 2010',
    'Population Estimate (as of July 1) - 2011',
    'Population Estimate (as of July 1) - 2012',
    'Population Estimate (as of July 1) - 2013',
    'Population Estimate (as of July 1) - 2014',
    'Population Estimate (as of July 1) - 2015',
    'Population Estimate (as of July 1) - 2016'
]


sum_p = pd.DataFrame(columns=['Year', 'Total'])


for column in estimate_columns:
    year = column.split('-')[-1].strip()  
    total = c1[column].sum()
    sum_p= sum_p.append({'Total': total}, ignore_index=True)


sum_p['Year'] = [int(year) for year in range(2010, 2017)]


sum_p.set_index('Year', inplace=True)


print(sum_p)

          Total
Year
2010  313069718
2011  315342090
2012  317632867
2013  319797985
2014  322098330
2015  324369799
2016  326538820

C:\Users\saket\AppData\Local\Temp\ipykernel_23804\55969965.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  sum_p= sum_p.append({'Total': total}, ignore_index=True)
C:\Users\saket\AppData\Local\Temp\ipykernel_23804\55969965.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  sum_p= sum_p.append({'Total': total}, ignore_index=True)
C:\Users\saket\AppData\Local\Temp\ipykernel_23804\55969965.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  sum_p= sum_p.append({'Total': total}, ignore_index=True)
C:\Users\saket\AppData\Local\Temp\ipykernel_23804\55969965.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  sum_p= sum_p.append({'Total': total}, ignore_index=True)
C:\Users\saket\AppData\Local\Temp\ipykernel_23804\55969965.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  sum_p= sum_p.append({'Total': total}, ignore_index=True)
C:\Users\saket\AppData\Local\Temp\ipykernel_23804\55969965.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  sum_p= sum_p.append({'Total': total}, ignore_index=True)
C:\Users\saket\AppData\Local\Temp\ipykernel_23804\55969965.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  sum_p= sum_p.append({'Total': total}, ignore_index=True)

#Challenge 2

In [102]:
import pandas as pd
import numpy as np

states = []
means = []
variances = []


for state in c1['Geography']:
    
    state_population = c1[c1['Geography'] == state][estimate_columns]
    
    state_mean = state_population.values.mean().astype(int)
    state_variance = state_population.values.var().astype(float)
    
    
    states.append(state)
    means.append(state_mean)
    variances.append(state_variance)


c2= pd.DataFrame({'State': states, 'Mean': means, 'Variance': variances})


largest_average_state = c2[c2['Mean'] == c2['Mean'].max()]


largest_variance_state = c2[c2['Variance'] == c2['Variance'].max()]


print("State with the largest average population:")
print(largest_average_state)

print("State with the largest variance in population:")
print(largest_variance_state)

print (c2)

State with the largest average population:
        State      Mean      Variance
4  California  38325798  4.190229e+11
State with the largest variance in population:
    State      Mean      Variance
43  Texas  26524695  7.720029e+11
                   State      Mean      Variance
0                Alabama   4827319  6.980728e+08
1                 Alaska    731574  8.358860e+07
2                Arizona   6645479  3.062786e+10
3               Arkansas   2957692  4.400948e+08
4             California  38325798  4.190229e+11
5               Colorado   5280498  2.702334e+10
6            Connecticut   3587520  4.632586e+07
7               Delaware    925888  3.114201e+08
8   District of Columbia    645814  6.344912e+08
9                Florida  19659760  3.402871e+11
10               Georgia  10003105  3.838584e+10
11                Hawaii   1401453  5.142520e+08
12                 Idaho   1618939  1.367061e+09
13              Illinois  12851431  6.051642e+08
14               Indiana   6564986  2.355295e+09
15                  Iowa   3092703  8.059650e+08
16                Kansas   2888543  2.960174e+08
17              Kentucky   4396847  8.399672e+08
18             Louisiana   4621248  2.128022e+09
19                 Maine   1329369  1.510507e+06
20              Maryland   5918813  5.900431e+09
21         Massachusetts   6698310  7.101824e+09
22              Michigan   9900244  3.712990e+08
23             Minnesota   5416287  4.774297e+09
24           Mississippi   2984918  5.430365e+07
25              Missouri   6043585  1.067289e+09
26               Montana   1015061  2.993955e+08
27              Nebraska   1868377  6.597383e+08
28                Nevada   2802503  6.589561e+09
29         New Hampshire   1324694  3.771646e+07
30            New Jersey   8888890  2.347449e+09
31            New Mexico   2079408  4.093287e+07
32              New York  19629924  1.448464e+10
33        North Carolina   9844859  3.778739e+10
34          North Dakota    720114  9.700098e+08
35                  Ohio  11574362  7.865358e+08
36              Oklahoma   3846260  3.241395e+09
37                Oregon   3945345  6.966803e+09
38          Pennsylvania  12768074  7.423337e+08
39          Rhode Island   1054033  1.953185e+06
40        South Carolina   4783088  1.202926e+10
41          South Dakota    842288  2.784527e+08
42             Tennessee   6499192  9.574607e+09
43                 Texas  26524695  7.720029e+11
44                  Utah   2904797  8.173002e+09
45               Vermont    626280  6.332679e+05
46              Virginia   8241045  1.676766e+10
47            Washington   6990209  3.147662e+10
48         West Virginia   1848523  7.431576e+07
49             Wisconsin   5739130  8.861932e+08
50               Wyoming    578197  6.742158e+07
51           Puerto Rico   3578169  1.068540e+10

#challenge 3

In [103]:
import pandas as pd
import numpy as np


population_data = c1[estimate_columns]



population_rate_of_change = np.diff(population_data, axis=1)

average_rate_of_change = abs(np.mean(population_rate_of_change, axis=1))


c3= pd.DataFrame({'State': c1['Geography'], 'Avg Rate of Change': average_rate_of_change})



print(c3)

                   State  Avg Rate of Change
0                Alabama        12968.000000
1                 Alaska         4643.833333
2                Arizona        87126.500000
3               Arkansas        11042.166667
4             California       319555.333333
5               Colorado        81983.500000
6            Connecticut          574.500000
7               Delaware         8708.166667
8   District of Columbia        12664.500000
9                Florida       293890.166667
10               Georgia        99475.000000
11                Hawaii        10768.666667
12                 Idaho        18688.333333
13              Illinois         6673.166667
14               Indiana        23754.166667
15                  Iowa        13992.500000
16                Kansas         8073.166667
17              Kentucky        14718.666667
18             Louisiana        22778.333333
19                 Maine          624.833333
20              Maryland        37977.166667
21         Massachusetts        41042.500000
22              Michigan         8467.500000
23             Minnesota        34800.833333
24           Mississippi         3067.333333
25              Missouri        16147.000000
26               Montana         8646.500000
27              Nebraska        12844.166667
28                Nevada        39462.333333
29         New Hampshire         2987.166667
30            New Jersey        23456.666667
31            New Mexico         2709.833333
32              New York        57108.166667
33        North Carolina        97978.833333
34          North Dakota        13904.333333
35                  Ohio        12231.666667
36              Oklahoma        27326.333333
37                Oregon        42569.500000
38          Pennsylvania        11980.666667
39          Rhode Island          514.833333
40        South Carolina        54196.000000
41          South Dakota         8188.166667
42             Tennessee        49087.166667
43                 Texas       436381.000000
44                  Utah        45981.833333
45               Vermont          231.333333
46              Virginia        64339.166667
47            Washington        90795.666667
48         West Virginia         3854.666667
49             Wisconsin        14740.833333
50               Wyoming         3498.000000
51           Puerto Rico        51703.000000

#Challenge 4

In [104]:

import pandas as pd


c4= pd.read_csv("C:/Users/saket/Downloads/2007-2016-Homelessnewss-USA.csv")
c4

,Year,State,CoC Number,CoC Name,Measures,Count
0,1/1/2007,AK,AK-500,Anchorage CoC,Chronically Homeless Individuals,224
1,1/1/2007,AK,AK-500,Anchorage CoC,Homeless Individuals,696
2,1/1/2007,AK,AK-500,Anchorage CoC,Homeless People in Families,278
3,1/1/2007,AK,AK-500,Anchorage CoC,Sheltered Chronically Homeless Individuals,187
4,1/1/2007,AK,AK-500,Anchorage CoC,Sheltered Homeless,842
...,...,...,...,...,...,...
86524,1/1/2016,WY,WY-500,Wyoming Statewide CoC,Unsheltered Homeless Unaccompanied Youth (Unde...,7
86525,1/1/2016,WY,WY-500,Wyoming Statewide CoC,Unsheltered Homeless Veterans,31
86526,1/1/2016,WY,WY-500,Wyoming Statewide CoC,Unsheltered Parenting Youth (Under 25),3
86527,1/1/2016,WY,WY-500,Wyoming Statewide CoC,Unsheltered Parenting Youth Age 18-24,3
86528,1/1/2016,WY,WY-500,Wyoming Statewide CoC,Unsheltered Parenting Youth Under 18,0

In [105]:
total_number_unique_coc_numbers = len(c4['CoC Number'].unique())
unique_CoC_number_and_names = c4[['CoC Number', 'CoC Name']].drop_duplicates()

print(f"Total Number = {total_number_unique_coc_numbers}")

print(unique_CoC_number_and_names.to_string(index=False, header=('CoC Number', 'CoC Name')))

Total Number = 414
CoC Number                                                                         CoC Name
    AK-500                                                                    Anchorage CoC
    AK-501                                                      Alaska Balance of State CoC
    AL-500                             Birmingham/Jefferson, St. Clair, Shelby Counties CoC
    AL-501                                          Mobile City & County/Baldwin County CoC
    AL-502                                                   Florence/Northwest Alabama CoC
    AL-503                                                     Huntsville/North Alabama CoC
    AL-504                                                     Montgomery City & County CoC
    AL-505                                                    Gadsden/Northeast Alabama CoC
    AL-506                                                     Tuscaloosa City & County CoC
    AL-507                                                     Alabama Balance of State CoC
    AR-500                                                 Little Rock/Central Arkansas CoC
    AR-501                                              Fayetteville/Northwest Arkansas CoC
    AR-502                                                     Conway/Arkansas River Valley
    AR-504                                                                  Delta Hills CoC
    AR-505                                                               Southeast Arkansas
    AR-506                                                     Johnson, Pope, Yell Counties
    AR-508                                                      Old Fort Homeless Coalition
    AR-509                                              Hot Springs/South West Arkansas CoC
    AR-510                            Hempstead, Sevier, Howard, Little River  Counties CoC
    AZ-500                                                     Arizona Balance of State CoC
    AZ-501                                                           Tucson/Pima County CoC
    AZ-502                                        Phoenix/Mesa/Maricopa County Regional CoC
    CA-500                                           San Jose/Santa Clara City & County CoC
    CA-501                                                                San Francisco CoC
    CA-502                                                       Oakland/Alameda County CoC
    CA-503                                                     Sacramento City & County CoC
    CA-504                                            Santa Rosa/Petaluma/Sonoma County CoC
    CA-505                                                 Richmond/Contra Costa County CoC
    CA-506                                        Salinas/Monterey, San Benito Counties CoC
    CA-507                                                                 Marin County CoC
    CA-508                                         Watsonville/Santa Cruz City & County CoC
    CA-509                                                             Mendocino County CoC
    CA-510                                            Turlock/Modesto/Stanislaus County CoC
    CA-511                                                  Stockton/San Joaquin County CoC
    CA-512                                                        Daly/San Mateo County CoC
    CA-513                                              Visalia, Kings, Tulare Counties CoC
    CA-514                                                         Fresno/Madera County CoC
    CA-515                                    Roseville/Rocklin/Placer, Nevada Counties CoC
    CA-516  Redding/Shasta, Siskiyou, Lassen, Plumas, Del Norte, Modoc, Sierra Counties CoC
    CA-517                                                           Napa City & County CoC
    CA-518                                                        Vallejo/Solano County CoC
    CA-519                                                  Chico/Paradise/Butte County CoC
    CA-520                                                         Merced City & County CoC
    CA-521                                                   Davis/Woodland/Yolo County CoC
    CA-522                                                              Humboldt County CoC
    CA-523                                              Colusa, Glenn, Trinity Counties CoC
    CA-524                                             Yuba City & County/Sutter County CoC
    CA-525                                                             El Dorado County CoC
    CA-526                            Amador, Calaveras, Tuolumne and Mariposa Counties CoC
    CA-600                                                    Los Angeles City & County CoC
    CA-601                                                    San Diego City and County CoC
    CA-602                                              Santa Ana/Anaheim/Orange County CoC
    CA-603                                             Santa Maria/Santa Barbara County CoC
    CA-604                                                      Bakersfield/Kern County CoC
    CA-606                                                                   Long Beach CoC
    CA-607                                                                     Pasadena CoC
    CA-608                                                      Riverside City & County CoC
    CA-609                                                 San Bernardino City & County CoC
    CA-611                                       Oxnard/San Buenaventura/Ventura County CoC
    CA-612                                                                     Glendale CoC
    CA-613                                                              Imperial County CoC
    CA-614                                                       San Luis Obispo County CoC
    CO-500                                                    Colorado Balance of State CoC
    CO-503                                          Metropolitan Denver Homeless Initiative
    CO-504                                              Colorado Springs/El Paso County CoC
    CT-503                                Bridgeport/Norwalk /Stamford/Fairfield County CoC
    CT-505                                                 Connecticut Balance of State CoC
    DC-500                                                         District of Columbia CoC
    DE-500                                                           Delaware Statewide CoC
    FL-500                                Sarasota/Bradenton/Manatee, Sarasota Counties CoC
    FL-501                                                    Tampa/Hillsborough County CoC
    FL-502                              St. Petersburg/Clearwater/Largo/Pinellas County CoC
    FL-503                                            Lakeland/Winter Haven/Polk County CoC
    FL-504                              Daytona Beach/Daytona/Volusia, Flagler Counties CoC
    FL-505                                  Fort Walton Beach/Okaloosa, Walton Counties CoC
    FL-506                                                      Tallahassee/Leon County CoC
    FL-507                                   Orlando/Orange, Osceola, Seminole Counties CoC
    FL-508                                         Gainesville/Alachua, Putnam Counties CoC
    FL-509                         Fort Pierce/St. Lucie, Indian River, Martin Counties CoC
    FL-510                                            Jacksonville-Duval, Clay Counties CoC
    FL-511                                         Pensacola/Escambia/Santa Rosa County CoC
    FL-512                                                           Saint Johns County CoC
    FL-513                                            Palm Bay/Melbourne/Brevard County CoC
    FL-514                                                          Ocala/Marion County CoC
    FL-515                                            Panama City/Bay, Jackson Counties CoC
    FL-517                                           Hendry, Hardee, Highlands Counties CoC
    FL-518                             Columbia, Hamilton, Lafayette, Suwannee Counties CoC
    FL-519                                                                 Pasco County CoC
    FL-520                                      Citrus, Hernando, Lake, Sumter Counties CoC
    FL-600                                                            Miami/Dade County CoC
    FL-601                                                 Ft Lauderdale/Broward County CoC
    FL-602                                                 Punta Gorda/Charlotte County CoC
    FL-603                                               Ft Myers/Cape Coral/Lee County CoC
    FL-604                                                                Monroe County CoC
    FL-605                                            West Palm Beach/Palm Beach County CoC
    FL-606                                                        Naples/Collier County CoC
    GA-500                                                        Atlanta Continuum of Care
    GA-501                                                     Georgia Balance of State CoC
    GA-503                                                         Athens/Clarke County CoC
    GA-504                                                                      Augusta CoC
    GA-505                                             Columbus-Muscogee/Russell County CoC
    GA-506                                                         Marietta/Cobb County CoC
    GA-507                                                      Savannah/Chatham County CoC
    GU-500                                                                         Guam CoC
    HI-500                                                      Hawaii Balance of State CoC
    HI-501                                                                     Honolulu CoC
    IA-500                                         Sioux City/Dakota, Woodbury Counties CoC
    IA-501                                                        Iowa Balance of State CoC
    IA-502                                                       Des Moines/Polk County CoC
    ID-500                                                             Boise/Ada County CoC
    ID-501                                                           Idaho Balance of State
    IL-500                                                               McHenry County CoC
    IL-501                                           Rockford/Winnebago, Boone Counties CoC
    IL-502                                           Waukegan/North Chicago/Lake County CoC
    IL-503                                    Champaign/Urbana/Rantoul/Champaign County CoC
    IL-504                                                               Madison County CoC
    IL-506                                               Joliet/Bolingbrook/Will County CoC
    IL-507                             Peoria/Perkin/Fulton, Peoria, Tazewell, Woodford CoC
    IL-508                               East Saint Louis/Belleville/Saint Clair County CoC
    IL-509                                                         Dekalb City & County CoC
    IL-510                                                                      Chicago CoC
    IL-511                                                                  Cook County CoC
    IL-512                                                 Bloomington/Central Illinois CoC
    IL-513                                                  Springfield/Sangamon County CoC
    IL-514                                                                DuPage County CoC
    IL-515                                                       South Central Illinois CoC
    IL-516                                                         Decatur/Macon County CoC
    IL-517                                                     Aurora/Elgin/Kane County CoC
    IL-518                                     Rock Island/Moline/Northwestern Illinois CoC
    IL-519                                                        West Central Illinois CoC
    IL-520                                                            Southern Illinois CoC
    IN-500                                       South Bend/Mishawaka/St. Joseph County CoC
    IN-502                                                     Indiana Balance of State CoC
    IN-503                                                                 Indianapolis CoC
    KS-502                                                      Wichita/Sedgwick County CoC
    KS-503                                                        Topeka/Shawnee County CoC
    KS-505                                         Overland Park/Shawnee/Johnson County CoC
    KS-507                                                      Kansas Balance of State CoC
    KY-500                                                    Kentucky Balance of State CoC
    KY-501                                                  Louisville/Jefferson County CoC
    KY-502                                                     Lexington/Fayette County CoC
    LA-500                                                           Lafayette/Acadiana CoC
    LA-502                                                 Shreveport/Bossier/Northwest CoC
    LA-503                                                 New Orleans/Jefferson Parish CoC
    LA-504                                                                  Baton Rouge CoC
    LA-505                                                   Monroe/Northeast Louisiana CoC
    LA-506                                                  Slidell/Southeast Louisiana CoC
    LA-507                                                 Alexandria/Central Louisiana CoC
    LA-508                                                   Houma-Terrebonne/Thibodaux CoC
    LA-509                                                       Louisiana Balance of State
    MA-500                                                                       Boston CoC
    MA-501                                Holyoke/Franklin, Hampden, Hampshire Counties CoC
    MA-502                                                                         Lynn CoC
    MA-503                                                             Cape Cod/Islands CoC
    MA-504                                                                  Springfield CoC
    MA-505                                                                  New Bedford CoC
    MA-506                                                      Worcester City & County CoC
    MA-507                                                  Pittsfield/Berkshire County CoC
    MA-508                                                                       Lowell CoC
    MA-509                                                                    Cambridge CoC
    MA-510                                      Gloucester/Haverhill/Salem/Essex County CoC
    MA-511                            Quincy/Brockton/Weymouth/Plymouth City and County CoC
    MA-514                                                           Framingham/Waltham CoC
    MA-515                                                                   Fall River CoC
    MA-516                                                   Massachusetts Balance of State
    MA-517                                                                   Somerville CoC
    MA-518                                                             Brookline/Newton CoC
    MA-519                                             Attleboro/Taunton/Bristol County CoC
    MD-500                                                   Cumberland/Allegany County CoC
    MD-501                                                               Baltimore City CoC
    MD-502                                                               Harford County CoC
    MD-503                                                Annapolis/Anne Arundel County CoC
    MD-504                                                                Howard County CoC
    MD-505                                                             Baltimore County CoC
    MD-506                                                               Carroll County CoC
    MD-507                                                                 Cecil County CoC
    MD-508                                         Charles, Calvert, St.Mary's Counties CoC
    MD-509                                                      Frederick City & County CoC
    MD-510                                                               Garrett County CoC
    MD-511                                                           Mid-Shore Regional CoC
    MD-512                                                 Hagerstown/Washington County CoC
    MD-513                                           Wicomico/Somerset/Worcester County CoC
    MD-600                                              Prince George`s County/Maryland CoC
    MD-601                                                            Montgomery County CoC
    ME-500                                                       Maine Balance of State CoC
    ME-502                                                                     Portland CoC
    MI-500                                                    Michigan Balance of State CoC
    MI-501                                                                      Detroit CoC
    MI-502                              Dearborn/Dearborn Heights/Westland/Wayne County CoC
    MI-503                                        St. Clair Shores/Warren/Macomb County CoC
    MI-504                                             Pontiac/Royal Oak/Oakland County CoC
    MI-505                                                         Flint/Genesee County CoC
    MI-506                                             Grand Rapids/Wyoming/Kent County CoC
    MI-507                                              Portage/Kalamazoo City & County CoC
    MI-508                                           Lansing/East Lansing/Ingham County CoC
    MI-509                                                   Ann Arbor/Washtenaw County CoC
    MI-510                                                        Saginaw City & County CoC
    MI-511                                                               Lenawee County CoC
    MI-512                                    Grand Traverse, Antrim, Leelanau Counties CoC
    MI-513                                                    Marquette, Alger Counties CoC
    MI-514                                                  Battle Creek/Calhoun County CoC
    MI-515                                                         Monroe City & County CoC
    MI-516                                         Norton Shores/Muskegon City & County CoC
    MI-517                                                        Jackson City & County CoC
    MI-518                                                            Livingston County CoC
    MI-519                                                        Holland/Ottawa County CoC
    MI-523                                                                 Eaton County CoC
    MN-500                                                  Minneapolis/Hennepin County CoC
    MN-501                                                     Saint Paul/Ramsey County CoC
    MN-502                                                Rochester/Southeast Minnesota CoC
    MN-503                                Dakota, Anoka, Washington, Scott, Carver Counties
    MN-504                                                          Northeast Minnesota CoC
    MN-505                                                  St. Cloud/Central Minnesota CoC
    MN-506                                                          Northwest Minnesota CoC
    MN-508                                              Moorhead/West Central Minnesota CoC
    MN-509                                                       Duluth/St.Louis County CoC

#Challenge 5

In [106]:

c4['Year'] = pd.to_datetime(c4['Year'], format='%m/%d/%Y')


years = c4['Year'].dt.year


unique_years = years.drop_duplicates()


formatted_years = ', '.join(str(year) for year in unique_years)


total_number_years = unique_years.count()

print(f"{formatted_years}\nTotal number of years = {total_number_years}")

2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016
Total number of years = 10

#Challenge 6

In [107]:
coc_500_data= c4[c4['CoC Number'].str.endswith('500')]

unique_years2 = coc_500_data['Year'].unique()
unique_states= coc_500_data['State'].unique()


years_list=[]
states_list=[]
total_homeless_count_list=[]
unsheltered_homeless_count_list = []

for year in unique_years2:
    for state in unique_states:
        c_half = coc_500_data[(coc_500_data['Year']==year) & (coc_500_data['State']==state)]
        
        total_homeless_count = c_half[c_half['Measures']== 'Total Homeless']['Count'].values[0]
        
        unsheltered_homeless_count = c_half[c_half['Measures']== 'Unsheltered Homeless']['Count'].values[0]
        
        years_list.append(year)
        states_list.append(state)
        total_homeless_count_list.append(total_homeless_count)
        unsheltered_homeless_count_list.append(unsheltered_homeless_count)
        
c6 = pd.DataFrame({
    'Year': years_list, 'State': states_list, 'Total Homeless Count': total_homeless_count_list, 'Unsheltered Homeless Count': unsheltered_homeless_count_list
})
print(c6)

          Year State Total Homeless Count Unsheltered Homeless Count
0   2007-01-01    AK                  974                        132
1   2007-01-01    AL                2,104                        864
2   2007-01-01    AR                1,822                        635
3   2007-01-01    AZ                2,997                      1,984
4   2007-01-01    CA                7,202                      5,101
..         ...   ...                  ...                        ...
505 2016-01-01    VT                  785                         94
506 2016-01-01    WA               10,730                      4,505
507 2016-01-01    WI                3,445                        132
508 2016-01-01    WV                   91                          3
509 2016-01-01    WY                  857                        366

[510 rows x 4 columns]

#Challenge 7

In [108]:

coc_500_data = c4[c4['CoC Number'].str.endswith('500')]

unique_years2 = coc_500_data['Year'].unique()

us_years_list = []
us_total_homeless_count_list = []
us_unsheltered_homeless_count_list = []

for year in unique_years2:
    c_year = coc_500_data[coc_500_data['Year'] == year]
    us_total_homeless_count = c_year[c_year['Measures']=='Total Homeless']['Count'].str.replace(',', '').astype(int).sum()
    us_unsheltered_homeless_count = c_year[c_year['Measures'] == 'Unsheltered Homeless']['Count'].str.replace(',', '').astype(int).sum()

    us_years_list.append(year)
    us_total_homeless_count_list.append(us_total_homeless_count)
    us_unsheltered_homeless_count_list.append(us_unsheltered_homeless_count)

c7 = pd.DataFrame({
    'Year': us_years_list,
    'Total Homeless Count': us_total_homeless_count_list,
    'Unsheltered Homeless Count': us_unsheltered_homeless_count_list
})
print(c7)

        Year  Total Homeless Count  Unsheltered Homeless Count
0 2007-01-01                104495                       33504
1 2008-01-01                108805                       34983
2 2009-01-01                112896                       36077
3 2010-01-01                113726                       36823
4 2011-01-01                111632                       37771
5 2012-01-01                111910                       39051
6 2013-01-01                101373                       29670
7 2014-01-01                101199                       27665
8 2015-01-01                101170                       29138
9 2016-01-01                 98937                       29313

#challenge 8

In [109]:

average_homeless_count = c7['Total Homeless Count'].mean()


std_deviation_homeless_count = c7['Total Homeless Count'].std()


max_annual_homeless_count = c7['Total Homeless Count'].max()
min_annual_homeless_count = c7['Total Homeless Count'].min()


year_max_total_homeless = c7[c7['Total Homeless Count'] == max_annual_homeless_count]['Year'].values[0]


year_min_total_homeless = c7[c7['Total Homeless Count'] == min_annual_homeless_count]['Year'].values[0]


print("Average homeless count estimated over all years:", average_homeless_count)
print("Standard deviation of total homeless counts:", std_deviation_homeless_count)
print("Maximum annual homeless count:", max_annual_homeless_count)
print("Minimum annual homeless count:", min_annual_homeless_count)
print("Year with the maximum total homeless count:", year_max_total_homeless)
print("Year with the minimum total homeless count:", year_min_total_homeless)

Average homeless count estimated over all years: 106614.3
Standard deviation of total homeless counts: 5753.515061826698
Maximum annual homeless count: 113726
Minimum annual homeless count: 98937
Year with the maximum total homeless count: 2010-01-01T00:00:00.000000000
Year with the minimum total homeless count: 2016-01-01T00:00:00.000000000